//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FURR.rc
//
#define IDOK2                           2
#define IDC_LOADPARAMS                  3
#define IDC_SAVEPARAMS                  4
#define IDCIDC_CHOOSEPREVIEW            5
#define IDC_CHOOSEPREVIEW               5
#define IDC_UPDATEPREVIEW               6
#define IDI_MAINICON                    106
#define IDD_SESSIONPREPARE              107
#define IDD_RUNSESSION                  110
#define IDC_CURSOR1                     113
#define IDC_INVISCURSOR                 113
#define IDC_INVISCUR                    115
#define IDD_ADJUSTPARAMS                116
#define IDR_MAINACCELERATOR             117
#define IDR_FURRMAIN                    118
#define IDD_CAMERACONTROLS              119
#define IDD_PREFERENCES                 120
#define IDD_AP_PAGEGLOBAL               122
#define IDD_AP_PAGERED                  123
#define IDD_AP_PAGEGREEN                124
#define IDD_AP_PAGEBLUE                 125
#define IDD_AP_PAGEWEDGE                126
#define IDD_AP_PAGEBW                   127
#define IDD_PAGEFULLIMAGE               128
#define IDD_AP_PAGEFULLIMAGE            128
#define IDC_PROGRESS                    1001
#define IDC_STATUSTEXT                  1002
#define IDC_LISTVIEW                    1003
#define IDC_ELAPSEDTIME                 1003
#define IDC_REMAININGTIME               1004
#define IDC_DONE                        1005
#define IDC_DISPLAYRES                  1007
#define IDC_FRAMERES                    1008
#define IDC_COLOURDEPTH                 1009
#define IDC_EXPOSURETIME                1010
#define IDC_RESOLUTION                  1013
#define IDC_BITDEPTH                    1014
#define IDC_BRIGHTNESS                  1015
#define IDC_SATURATION                  1016
#define IDC_HUE                         1017
#define IDC_REDINTENSITY                1018
#define IDC_GREENINTENSITY              1019
#define IDC_BLUEINTENSITY               1020
#define IDC_HSV                         1021
#define IDC_RGB                         1022
#define IDC_REDGAMMA                    1023
#define IDC_GREENGAMMA                  1024
#define IDC_WHOREGAMMA                  1024
#define IDC_BLUEGAMMA                   1025
#define IDC_CONTRAST                    1027
#define IDC_LBLBRIGHTNESS               1029
#define IDC_LBLSATURATION               1030
#define IDC_LBLHUE                      1031
#define IDC_LBLREDINTENSITY             1032
#define IDC_LBLGREENINTENSITY           1033
#define IDC_LBLBLUEINTENSITY            1034
#define IDC_LBLREDGAMMA                 1035
#define IDC_LBLGREENGAMMA               1036
#define IDC_LBLBLUEGAMMA                1037
#define IDD_FURRMAINDLG                 1038
#define IDC_LOADDEFAULTS                1040
#define IDC_CHKVISTA                    1043
#define IDC_CHKVISTAMODE                1043
#define IDC_MOVEVAL                     1046
#define IDC_FASTREV                     1047
#define IDC_FASTFWD                     1048
#define IDC_STEPREV                     1049
#define IDC_ANYSTRING                   1050
#define IDC_STEPFWD                     1051
#define IDC_LBLANYSTRING                1052
#define IDC_SENDANYSTRING               1053
#define IDC_IE                          1055
#define IDC_FRAMECOUNTER                1056
#define IDC_LBLEXPOSURETIME             1057
#define IDC_LBLEXPOSUREDELAY            1058
#define IDC_LBLFRAMECOUNTER             1059
#define IDC_CHKLOCKSETTINGS             1060
#define IDC_ID                          1062
#define IDC_IESTART                     1063
#define IDC_IEEND                       1064
#define IDC_IESTEP                      1065
#define IDC_CHOOSELUT                   1068
#define IDC_LUTFILE                     1069
#define IDC_CLEARLUT                    1071
#define IDC_TREEVIEW                    1072
#define IDC_ET                          1076
#define IDC_ED                          1077
#define IDC_GAMMA                       1078
#define IDC_CUSTOM1                     1079
#define IDC_STEPEXPOSURETIME            1082
#define IDC_ENDEXPOSURETIME             1083
#define IDC_WEDGEFILE                   1085
#define IDC_BROWSE                      1086
#define IDC_STARTEXPOSURETIME           1087
#define IDC_EDIT4                       1088
#define IDC_STEPS                       1088
#define IDC_COLORWHEEL                  1089
#define IDC_CHANNELSPLIT                1090
#define IDC_MODE                        1091
#define IDC_FULLIMAGE                   1092
#define IDC_WINDFWD                     1094
#define IDC_WINDFWDFRAMES               1095
#define IDC_WINDREV                     1096
#define IDC_WINDREVFRAMES               1097
#define IDC_ZEROACCUMULATOR             1098
#define IDI_FRS_ERROR                   32513
#define IDI_FRS_WARNING                 32515
#define IDI_FRS_INFORMATION             32516
#define ID_FILE_EXIT                    40001
#define ID_TOOLS_ADJUSTCOLOUR           40005
#define ID_FILE_NEWSESSION              40008
#define ID_TOOLS_CAMERACONTROLS         40009
#define ID_FILE_NEWWEDGESESSION         40010
#define ID_TOOLS_PREFERENCES            40011
#define ID_FILE_SAVECURRENTLOG          40012
#define ID_LOG_CLEARLOG                 40013
#define ID_LOG_SAVELOG                  40014
#define ID_TOOLS_SESSIONSETTINGS        40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
